### PR TITLE
Add code coverage support

### PR DESCRIPTION
**Pull request by smspillaz**
[endlessm/eos-shell#2264]

### CODE REVIEW

**Comment by ptomato** [comment]
Coverage measures correctly with this pull request, but there are a couple issues with the generated HTML report:

- `tests` should be in the coverage blacklist.
- Arguably, `emer-event-recorder-server.c` could be as well, because it's autogenerated.
- Clicking on any of the source files in order to see which lines got hit, produces "(missing file)". Probably because the paths are duplicated - `tests/tests` and `eosmetrics/eosmetrics` instead of `tests` and `eosmetrics`.

**Comment by smspillaz** [comment]
@ptomato Items 1 and 2 are resolved. As for the duplication, I'd suggest re-trying with endlessm/eos-sdk#2640 .

**Comment by ptomato** [comment]
I'm still getting a duplicated `eosmetrics/eosmetrics` using the updated `eos-coverage.m4`, unfortunately.

**Comment by ptomato** [comment]
**CR pass** - Problem fixed after upgrading lcov.

**Pull request merged**
