### PR TITLE
dbus: Add ResetTrackingId method

### PR DESCRIPTION
**Pull request by smspillaz**
We'll need this in order to reload the config later.

https://phabricator.endlessm.com/T18983

### CODE REVIEW

**Comment by ptomato** [comment]
What is this for? If the machine-id is changing during the daemon's lifetime then you have more serious problems than the daemon crashing...

**Comment by smspillaz** [comment]
@ptomato In this case, we are deliberately resetting the machine-id for demo mode. So we want event-recorder to reload the machine-id on demand.

**Comment by ptomato** [comment]
I think that is going to break a *lot* of other things that assume the machine ID is permanent.

**Comment by ptomato** [comment]
I ran across this in the `dbus-uuidgen` manpage while I was trying to figure out something else for dbus-in-a-flatpak-sandbox, it's relevant:

> If you try to change an existing machine-id on a running system, it
> will probably result in bad things happening. Don't try to change this
> file. Also, don't make it the same on two different systems; it needs
> to be different anytime there are two different kernels running.

**Comment by smspillaz** [comment]
Okay, changed the approach here - we now have a `ResetTrackingId` method which `eos-event-recorder-daemon` handles in a slightly more clever way.

**Pull request merged**
