### PR TITLE
Make smoke tests executable and add shebang line.

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
[endlessm/eos-sdk#3151]

### CODE REVIEW

**Comment by Kurt-von-Laven** [comment]
This PR is not intended to be cherry-picked to eos2.4 but can be for the sake of convenience.

**Comment by ptomato** [comment]
**CR pass**

**Comment by ptomato** [comment]
@Kurt-von-Laven You need to remove `tests/smoke-tests/event-types.js` from `EXTRA_DIST`.

**Comment by Kurt-von-Laven** [comment]
@ptomato Oops; fixed in https://github.com/endlessm/eos-metrics/pull/28.

**Comment by ptomato** [comment]
Thank you.

**Pull request merged**
